# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'okno_new.ui'
#
# Created: Sun Jul 19 23:20:59 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_GCS(object):
    def setupUi(self, GCS):
        GCS.setObjectName("GCS")
        GCS.resize(821, 600)
        self.centralwidget = QtGui.QWidget(GCS)
        self.centralwidget.setObjectName("centralwidget")
        self.window_CYK = QtGui.QTabWidget(self.centralwidget)
        self.window_CYK.setGeometry(QtCore.QRect(150, 10, 631, 491))
        self.window_CYK.setObjectName("window_CYK")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.window_cyk = QtGui.QTextBrowser(self.tab)
        self.window_cyk.setGeometry(QtCore.QRect(0, 0, 631, 471))
        self.window_cyk.setObjectName("window_cyk")
        self.window_CYK.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.window_grammar = QtGui.QTextBrowser(self.tab_2)
        self.window_grammar.setGeometry(QtCore.QRect(0, 0, 631, 471))
        self.window_grammar.setObjectName("window_grammar")
        self.window_CYK.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.window_file = QtGui.QTextBrowser(self.tab_3)
        self.window_file.setGeometry(QtCore.QRect(0, 0, 631, 471))
        self.window_file.setObjectName("window_file")
        self.window_CYK.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.numberOfLoops = QtGui.QSpinBox(self.tab_4)
        self.numberOfLoops.setGeometry(QtCore.QRect(70, 30, 42, 22))
        self.numberOfLoops.setMaximum(10000)
        self.numberOfLoops.setProperty("value", QtCore.QVariant(1))
        self.numberOfLoops.setObjectName("numberOfLoops")
        self.label = QtGui.QLabel(self.tab_4)
        self.label.setGeometry(QtCore.QRect(10, 30, 61, 20))
        self.label.setObjectName("label")
        self.propertiesAccept = QtGui.QPushButton(self.tab_4)
        self.propertiesAccept.setGeometry(QtCore.QRect(540, 430, 75, 23))
        self.propertiesAccept.setObjectName("propertiesAccept")
        self.propertiesCancel = QtGui.QPushButton(self.tab_4)
        self.propertiesCancel.setGeometry(QtCore.QRect(450, 430, 75, 23))
        self.propertiesCancel.setObjectName("propertiesCancel")
        self.label_2 = QtGui.QLabel(self.tab_4)
        self.label_2.setGeometry(QtCore.QRect(150, 30, 61, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.tab_4)
        self.label_3.setGeometry(QtCore.QRect(150, 50, 61, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(150, 70, 61, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(150, 90, 61, 20))
        self.label_5.setObjectName("label_5")
        self.Pk = QtGui.QDoubleSpinBox(self.tab_4)
        self.Pk.setGeometry(QtCore.QRect(180, 30, 62, 22))
        self.Pk.setDecimals(2)
        self.Pk.setMaximum(1.0)
        self.Pk.setSingleStep(0.01)
        self.Pk.setProperty("value", QtCore.QVariant(0.0))
        self.Pk.setObjectName("Pk")
        self.Pm = QtGui.QDoubleSpinBox(self.tab_4)
        self.Pm.setGeometry(QtCore.QRect(180, 50, 62, 22))
        self.Pm.setMaximum(1.0)
        self.Pm.setSingleStep(0.01)
        self.Pm.setObjectName("Pm")
        self.Pi = QtGui.QDoubleSpinBox(self.tab_4)
        self.Pi.setGeometry(QtCore.QRect(180, 70, 62, 22))
        self.Pi.setMaximum(1.0)
        self.Pi.setSingleStep(0.01)
        self.Pi.setObjectName("Pi")
        self.Pa = QtGui.QDoubleSpinBox(self.tab_4)
        self.Pa.setGeometry(QtCore.QRect(180, 90, 62, 22))
        self.Pa.setMaximum(1.0)
        self.Pa.setSingleStep(0.01)
        self.Pa.setObjectName("Pa")
        self.label_6 = QtGui.QLabel(self.tab_4)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 61, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(self.tab_4)
        self.label_7.setGeometry(QtCore.QRect(130, 10, 111, 20))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtGui.QLabel(self.tab_4)
        self.label_8.setGeometry(QtCore.QRect(270, 10, 111, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtGui.QLabel(self.tab_4)
        self.label_9.setGeometry(QtCore.QRect(270, 30, 61, 20))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtGui.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(270, 50, 61, 20))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtGui.QLabel(self.tab_4)
        self.label_11.setGeometry(QtCore.QRect(270, 70, 61, 20))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtGui.QLabel(self.tab_4)
        self.label_12.setGeometry(QtCore.QRect(270, 90, 61, 20))
        self.label_12.setObjectName("label_12")
        self.cs = QtGui.QSpinBox(self.tab_4)
        self.cs.setGeometry(QtCore.QRect(300, 50, 42, 22))
        self.cs.setMinimum(1)
        self.cs.setMaximum(30)
        self.cs.setObjectName("cs")
        self.cf = QtGui.QSpinBox(self.tab_4)
        self.cf.setGeometry(QtCore.QRect(300, 30, 42, 22))
        self.cf.setMinimum(1)
        self.cf.setMaximum(30)
        self.cf.setObjectName("cf")
        self.ba = QtGui.QSpinBox(self.tab_4)
        self.ba.setGeometry(QtCore.QRect(300, 70, 42, 22))
        self.ba.setMaximum(15)
        self.ba.setObjectName("ba")
        self.raf = QtGui.QSpinBox(self.tab_4)
        self.raf.setGeometry(QtCore.QRect(300, 90, 42, 22))
        self.raf.setMaximum(15)
        self.raf.setObjectName("raf")
        self.label_13 = QtGui.QLabel(self.tab_4)
        self.label_13.setGeometry(QtCore.QRect(10, 150, 61, 20))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtGui.QLabel(self.tab_4)
        self.label_14.setGeometry(QtCore.QRect(10, 170, 61, 20))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtGui.QLabel(self.tab_4)
        self.label_15.setGeometry(QtCore.QRect(10, 190, 61, 20))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtGui.QLabel(self.tab_4)
        self.label_16.setGeometry(QtCore.QRect(10, 210, 61, 20))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtGui.QLabel(self.tab_4)
        self.label_17.setGeometry(QtCore.QRect(10, 230, 61, 20))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtGui.QLabel(self.tab_4)
        self.label_18.setGeometry(QtCore.QRect(10, 250, 61, 20))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtGui.QLabel(self.tab_4)
        self.label_19.setGeometry(QtCore.QRect(10, 290, 61, 20))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtGui.QLabel(self.tab_4)
        self.label_20.setGeometry(QtCore.QRect(10, 270, 61, 20))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtGui.QLabel(self.tab_4)
        self.label_21.setGeometry(QtCore.QRect(10, 310, 61, 20))
        self.label_21.setObjectName("label_21")
        self.ts = QtGui.QSpinBox(self.tab_4)
        self.ts.setGeometry(QtCore.QRect(60, 170, 42, 22))
        self.ts.setMinimum(1)
        self.ts.setMaximum(30)
        self.ts.setObjectName("ts")
        self.np = QtGui.QSpinBox(self.tab_4)
        self.np.setGeometry(QtCore.QRect(60, 190, 42, 22))
        self.np.setMinimum(1)
        self.np.setObjectName("np")
        self.nstart = QtGui.QSpinBox(self.tab_4)
        self.nstart.setGeometry(QtCore.QRect(60, 210, 42, 22))
        self.nstart.setMinimum(1)
        self.nstart.setObjectName("nstart")
        self.nN = QtGui.QSpinBox(self.tab_4)
        self.nN.setGeometry(QtCore.QRect(60, 230, 42, 22))
        self.nN.setMinimum(1)
        self.nN.setMaximum(30)
        self.nN.setObjectName("nN")
        self.nelit = QtGui.QSpinBox(self.tab_4)
        self.nelit.setGeometry(QtCore.QRect(60, 270, 42, 22))
        self.nelit.setMinimum(1)
        self.nelit.setObjectName("nelit")
        self.nT = QtGui.QSpinBox(self.tab_4)
        self.nT.setGeometry(QtCore.QRect(60, 250, 42, 22))
        self.nT.setMinimum(1)
        self.nT.setObjectName("nT")
        self.nrun = QtGui.QSpinBox(self.tab_4)
        self.nrun.setGeometry(QtCore.QRect(60, 290, 42, 22))
        self.nrun.setMinimum(10)
        self.nrun.setMaximum(50)
        self.nrun.setObjectName("nrun")
        self.nmax = QtGui.QSpinBox(self.tab_4)
        self.nmax.setGeometry(QtCore.QRect(60, 310, 42, 22))
        self.nmax.setMinimum(1)
        self.nmax.setMaximum(50000)
        self.nmax.setObjectName("nmax")
        self.label_22 = QtGui.QLabel(self.tab_4)
        self.label_22.setGeometry(QtCore.QRect(160, 170, 61, 20))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtGui.QLabel(self.tab_4)
        self.label_23.setGeometry(QtCore.QRect(160, 190, 61, 20))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtGui.QLabel(self.tab_4)
        self.label_24.setGeometry(QtCore.QRect(160, 210, 61, 20))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtGui.QLabel(self.tab_4)
        self.label_25.setGeometry(QtCore.QRect(160, 230, 61, 20))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtGui.QLabel(self.tab_4)
        self.label_26.setGeometry(QtCore.QRect(160, 250, 61, 20))
        self.label_26.setObjectName("label_26")
        self.wp = QtGui.QSpinBox(self.tab_4)
        self.wp.setGeometry(QtCore.QRect(180, 170, 42, 22))
        self.wp.setMinimum(1)
        self.wp.setMaximum(20)
        self.wp.setObjectName("wp")
        self.wn = QtGui.QSpinBox(self.tab_4)
        self.wn.setGeometry(QtCore.QRect(180, 190, 42, 22))
        self.wn.setMinimum(1)
        self.wn.setMaximum(20)
        self.wn.setObjectName("wn")
        self.wc = QtGui.QSpinBox(self.tab_4)
        self.wc.setGeometry(QtCore.QRect(180, 210, 42, 22))
        self.wc.setMinimum(1)
        self.wc.setMaximum(20)
        self.wc.setObjectName("wc")
        self.wf = QtGui.QSpinBox(self.tab_4)
        self.wf.setGeometry(QtCore.QRect(180, 230, 42, 22))
        self.wf.setMinimum(1)
        self.wf.setMaximum(15)
        self.wf.setObjectName("wf")
        self.f0 = QtGui.QSpinBox(self.tab_4)
        self.f0.setGeometry(QtCore.QRect(180, 250, 42, 22))
        self.f0.setMaximum(10)
        self.f0.setObjectName("f0")
        self.window_CYK.addTab(self.tab_4, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_27 = QtGui.QLabel(self.tab_5)
        self.label_27.setGeometry(QtCore.QRect(110, 60, 281, 21))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtGui.QLabel(self.tab_5)
        self.label_28.setGeometry(QtCore.QRect(110, 140, 181, 16))
        self.label_28.setObjectName("label_28")
        self.button_ok = QtGui.QPushButton(self.tab_5)
        self.button_ok.setGeometry(QtCore.QRect(120, 220, 80, 27))
        self.button_ok.setObjectName("button_ok")
        self.label_29 = QtGui.QLabel(self.tab_5)
        self.label_29.setGeometry(QtCore.QRect(110, 170, 181, 21))
        self.label_29.setObjectName("label_29")
        self.button_anuluj = QtGui.QPushButton(self.tab_5)
        self.button_anuluj.setGeometry(QtCore.QRect(230, 220, 80, 27))
        self.button_anuluj.setObjectName("button_anuluj")
        self.patter = QtGui.QLineEdit(self.tab_5)
        self.patter.setGeometry(QtCore.QRect(110, 80, 271, 21))
        self.patter.setObjectName("patter")
        self.min_lenght = QtGui.QSpinBox(self.tab_5)
        self.min_lenght.setGeometry(QtCore.QRect(330, 140, 54, 23))
        self.min_lenght.setObjectName("min_lenght")
        self.max_lenght = QtGui.QSpinBox(self.tab_5)
        self.max_lenght.setGeometry(QtCore.QRect(330, 110, 54, 21))
        self.max_lenght.setObjectName("max_lenght")
        self.collection_size = QtGui.QSpinBox(self.tab_5)
        self.collection_size.setGeometry(QtCore.QRect(330, 170, 54, 23))
        self.collection_size.setObjectName("collection_size")
        self.label_30 = QtGui.QLabel(self.tab_5)
        self.label_30.setGeometry(QtCore.QRect(110, 110, 181, 21))
        self.label_30.setObjectName("label_30")
        self.window_CYK.addTab(self.tab_5, "")
        self.start_GLBS = QtGui.QPushButton(self.centralwidget)
        self.start_GLBS.setGeometry(QtCore.QRect(10, 60, 121, 31))
        self.start_GLBS.setObjectName("start_GLBS")
        self.Pause = QtGui.QPushButton(self.centralwidget)
        self.Pause.setGeometry(QtCore.QRect(10, 100, 121, 31))
        self.Pause.setObjectName("Pause")
        self.params = QtGui.QPushButton(self.centralwidget)
        self.params.setGeometry(QtCore.QRect(10, 140, 121, 31))
        self.params.setObjectName("params")
        self.open_file = QtGui.QPushButton(self.centralwidget)
        self.open_file.setGeometry(QtCore.QRect(10, 20, 121, 31))
        self.open_file.setObjectName("open_file")
        self.Koniec = QtGui.QPushButton(self.centralwidget)
        self.Koniec.setGeometry(QtCore.QRect(10, 510, 121, 31))
        self.Koniec.setObjectName("Koniec")
        self.change_word = QtGui.QPushButton(self.centralwidget)
        self.change_word.setGeometry(QtCore.QRect(10, 180, 121, 31))
        self.change_word.setObjectName("change_word")
        self.create_test = QtGui.QPushButton(self.centralwidget)
        self.create_test.setGeometry(QtCore.QRect(10, 220, 121, 31))
        self.create_test.setObjectName("create_test")
        GCS.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(GCS)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 821, 22))
        self.menubar.setObjectName("menubar")
        self.menuOpcje = QtGui.QMenu(self.menubar)
        self.menuOpcje.setObjectName("menuOpcje")
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        GCS.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(GCS)
        self.statusbar.setObjectName("statusbar")
        GCS.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(GCS)
        self.toolBar.setObjectName("toolBar")
        GCS.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtGui.QToolBar(GCS)
        self.toolBar_2.setObjectName("toolBar_2")
        GCS.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.actionWczytaj_Dane = QtGui.QAction(GCS)
        self.actionWczytaj_Dane.setObjectName("actionWczytaj_Dane")
        self.menuOpcje.addAction(self.actionWczytaj_Dane)
        self.menubar.addAction(self.menuOpcje.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(GCS)
        self.window_CYK.setCurrentIndex(4)
        QtCore.QObject.connect(self.Koniec, QtCore.SIGNAL("clicked()"), GCS.close)
        QtCore.QMetaObject.connectSlotsByName(GCS)

    def retranslateUi(self, GCS):
        GCS.setWindowTitle(QtGui.QApplication.translate("GCS", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.window_CYK.setTabText(self.window_CYK.indexOf(self.tab), QtGui.QApplication.translate("GCS", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.window_CYK.setTabText(self.window_CYK.indexOf(self.tab_2), QtGui.QApplication.translate("GCS", "Tab 2", None, QtGui.QApplication.UnicodeUTF8))
        self.window_CYK.setTabText(self.window_CYK.indexOf(self.tab_3), QtGui.QApplication.translate("GCS", "Strona", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("GCS", "Liczba pętli", None, QtGui.QApplication.UnicodeUTF8))
        self.propertiesAccept.setText(QtGui.QApplication.translate("GCS", "Akceptuj", None, QtGui.QApplication.UnicodeUTF8))
        self.propertiesCancel.setText(QtGui.QApplication.translate("GCS", "Anuluj", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("GCS", "Pk", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("GCS", "Pm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("GCS", "Pi", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("GCS", "Pa", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("GCS", "Ogólne:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("GCS", "Algorytm gentyczny:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("GCS", "Algorytm ścisku:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("GCS", "cf", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("GCS", "cs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("GCS", "ba", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("GCS", "raf", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("GCS", "Pozostałe:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("GCS", "ts", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("GCS", "np", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("GCS", "nstart", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("GCS", "nN", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("GCS", "nT", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("GCS", "nrun", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("GCS", "nelit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("GCS", "nmax", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("GCS", "wp", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("GCS", "wn", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("GCS", "wc", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("GCS", "wf", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("GCS", "f0", None, QtGui.QApplication.UnicodeUTF8))
        self.window_CYK.setTabText(self.window_CYK.indexOf(self.tab_4), QtGui.QApplication.translate("GCS", "Strona", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("GCS", "Podaj wzór gramatyki w formacie a^n*b^n:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("GCS", "minimalna dlugosc zdania:", None, QtGui.QApplication.UnicodeUTF8))
        self.button_ok.setText(QtGui.QApplication.translate("GCS", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("GCS", "ilosc zdan uczacych:", None, QtGui.QApplication.UnicodeUTF8))
        self.button_anuluj.setText(QtGui.QApplication.translate("GCS", "Anuluj", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("GCS", "maksymalna dlugosc zdania:", None, QtGui.QApplication.UnicodeUTF8))
        self.window_CYK.setTabText(self.window_CYK.indexOf(self.tab_5), QtGui.QApplication.translate("GCS", "Strona", None, QtGui.QApplication.UnicodeUTF8))
        self.start_GLBS.setText(QtGui.QApplication.translate("GCS", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.Pause.setText(QtGui.QApplication.translate("GCS", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.params.setText(QtGui.QApplication.translate("GCS", "Zmień parametry", None, QtGui.QApplication.UnicodeUTF8))
        self.open_file.setText(QtGui.QApplication.translate("GCS", "Wczytaj plik", None, QtGui.QApplication.UnicodeUTF8))
        self.Koniec.setText(QtGui.QApplication.translate("GCS", "Koniec", None, QtGui.QApplication.UnicodeUTF8))
        self.change_word.setText(QtGui.QApplication.translate("GCS", "Następny krok", None, QtGui.QApplication.UnicodeUTF8))
        self.create_test.setText(QtGui.QApplication.translate("GCS", "Generuj zdania", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOpcje.setTitle(QtGui.QApplication.translate("GCS", "Opcje", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("GCS", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("GCS", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar_2.setWindowTitle(QtGui.QApplication.translate("GCS", "toolBar_2", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWczytaj_Dane.setText(QtGui.QApplication.translate("GCS", "Wczytaj Dane", None, QtGui.QApplication.UnicodeUTF8))

